export const PoolDataLists = [
  {
    title: "Cricket World Cup",
    topic: "Cricket",
    type: "Mega",
    totalPoolAmount: "50 CRORES",
    joinedPlayers: "836596",
    maxPlayers: "1253132",
    entryFee: 399,
    winningChance: 70,
    firstPrize: "2.5 Crore",
  },
  {
    title: "Football League",
    topic: "Football",
    totalPoolAmount: "45 CRORES",
    joinedPlayers: "438296",
    maxPlayers: "643776",
    entryFee: 699,
    winningChance: 73,
    firstPrize: "2.25 Crore",
  },
  {
    title: "Finance Quiz",
    topic: "Finance",
    totalPoolAmount: "40 CRORES",
    joinedPlayers: "336777",
    maxPlayers: "572246",
    entryFee: 699,
    winningChance: 73,
    firstPrize: "2 Crore",
  },
  {
    title: "Bollywood Trivia",
    topic: "Bollywood",
    totalPoolAmount: "35 CRORES",
    joinedPlayers: "681399",
    maxPlayers: "877192",
    entryFee: 399,
    winningChance: 70,
    firstPrize: "1.75 Crore",
  },
  {
    title: "Stock Market Challenge",
    topic: "Stocks",
    totalPoolAmount: "30 CRORES",
    joinedPlayers: "236035",
    maxPlayers: "429184",
    entryFee: 699,
    winningChance: 73,
    firstPrize: "1.5 Crore",
  },
  {
    title: "Mathematical Genius",
    topic: "Mathematics",
    totalPoolAmount: "25 CRORES",
    joinedPlayers: "419428",
    maxPlayers: "626566",
    entryFee: 399,
    winningChance: 75,
    firstPrize: "1.25 Crore",
  },
  {
    title: "Famous Personalities",
    topic: "Personalities",
    totalPoolAmount: "20 CRORES",
    joinedPlayers: "178458",
    maxPlayers: "286123",
    entryFee: 699,
    winningChance: 75,
    firstPrize: "1 Crore",
  },
  {
    title: "Music Battle",
    topic: "Music",
    totalPoolAmount: "15 CRORES",
    joinedPlayers: "199815",
    maxPlayers: "300601",
    entryFee: 499,
    winningChance: 71,
    firstPrize: "75 Lakhs",
  },
  {
    title: "History Buff",
    topic: "History",
    totalPoolAmount: "10 CRORES",
    joinedPlayers: "187694",
    maxPlayers: "250626",
    entryFee: 399,
    winningChance: 70,
    firstPrize: "50 Lakhs",
  },
  {
    title: "Geography Explorer",
    topic: "Geography",
    totalPoolAmount: "5 CRORES",
    joinedPlayers: "153413",
    maxPlayers: "251256",
    entryFee: 199,
    winningChance: 72,
    firstPrize: "50 Lakhs",
  },
];
